name: 'red-cat-pictures-dev'
services:
  app:
    build: .
    restart: on-failure:3
    # runtime: nvidia # Enable NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    volumes:
      - red-cat-pictures_static:/app/static
      - type: bind
        source: ./.data
        target: /app/.data
    env_file:
      - .env.prod
    ports:
      - 4300:3000
  # directus:
  #   image: directus/directus:11
  #   ports:
  #     - 8055:8055
  #   volumes:
  #     - ./directus/database:/directus/database
  #     - ./directus/uploads:/directus/uploads
  #     - ./directus/extensions:/directus/extensions
  #   environment:
  #     SECRET: 'replace-with-secure-random-value'
  #     ADMIN_EMAIL: 'admin@example.com'
  #     ADMIN_PASSWORD: 'd1r3ctu5'
  #     DB_CLIENT: 'sqlite3'
  #     DB_FILENAME: '/directus/database/data.db'
  #     WEBSOCKETS_ENABLED: 'true'

volumes:
  red-cat-pictures_static:
    external: true
