version: '3.9'
services:
  app:
    image: 'ghcr.io/algostract/red-cat-pictures:latest'
    volumes:
      - red-cat-pictures_static:/app/static
    env_file:
      - .env.prod
    ports:
      - 4300:3000
    networks:
      - front-tier
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  red-cat-pictures_static:
    external: true

networks:
  front-tier:
    driver: overlay
