name: 'red-cat-pictures'
services:
  app:
    image: 'ghcr.io/algostract/red-cat-pictures:latest'
    restart: on-failure:3
    # runtime: nvidia # Enable NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
    volumes:
      - type: bind
        source: ./static
        target: /app/static
    env_file:
      - .env.prod
    ports:
      - 4102:3000
