version: '3.9'
services:
  cloudreve:
    image: cloudreve/cloudreve:latest
    env_file:
      - .env
    volumes:
      - backend_data:/cloudreve/data
    expose:
      - 5212
    networks:
      - front-tier
    depends_on:
      - postgresql
      - redis
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  postgresql:
    image: postgres:17
    env_file:
      - .env
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - front-tier
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - front-tier
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  backend_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/cloudreve/data
  database_postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/cloudreve/postgres
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/cloudreve/redis

networks:
  front-tier:
    driver: overlay
